version: '3.8'

services:
  app:
    build: .
    ports:
      - "5175:80"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - SUPABASE_URL=http://localhost:8000
      - SUPABASE_KEY=your-supabase-key
    networks:
      - web

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - web

  supabase:
    image: supabase/postgres:latest
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - supabase_data:/var/lib/postgresql/data
    networks:
      - web

volumes:
  postgres_data:
  supabase_data:

networks:
  web:
    name: web
    external: true
